### ISSUE TITLE
Manuális kódátvizsgálás elvégzése

### ISSUE THREAD

**Issue by Tajtesz** [BME-MIT-IET/Immutable-iet-2018#2]
Feladatok:

- [x]  Kódátvizsgálás a kollekció fájlokban
- [x]  Eredmények dokumentálása a feladathoz tartozó wiki oldalon
- [x]  Esetleges hibák javítása/refaktor

**Comment by lbzs** [comment]
A forrásfájlokat vizsgálva a következő dologra lettem figyelmes. 

`static of(/*...values*/) {
    return this(arguments);
  }`

Sok helyen a függvények argumentában egy kommentezett rész szerepel, ezeknek van jelentősségük, vagy töröljük őket?

**Comment by Tajtesz** [comment]
Javascriptben egy függvénynek híváskor átadhatunk több/kevesebb paramétert, mint amennyit vár. Jelen esetben többet fogunk átadni, hiszen ha a kommentet nem vesszük figyelembe, akkor a függvény így néz ki:
`static of() {...}`

Az átadott paramétereket viszont elérhetjük a függvényen belül az `arguments` tömböt használva, amit láthatóan használ is ez a függvény.

Tehát ez a `/*...values*/` komment csak azt jelzi, hogy esetlegesen több értéket is várunk. Ez azonban csak jelzésértékű, célja csak annyi, hogy olvashatóbbá tegye a kódot.

Szerintem maradjon így.

**Comment by lbzs** [comment]
A következő forrásfájlokban a fájl végén találtam konstans illetve változó deklarációt. Ez szembemegy azzal a kovencióval, miszerint a változók deklarálása a fájlok elején történik.

- Repeat.js
- Hash.js
- Map.js
- Predicate.js
- Range.js

Ti mit gondoltok erről?

**Comment by Tajtesz** [comment]
Abszolút jogos, rontja a kód olvashatóságát. Szerintem mindenképp javítsd. Viszont ha ezeket módosítod, akkor nyomj majd a végén egy `npm test`-et, nehogy elromoljon valami :slightly_smiling_face:

**Comment by lbzs** [comment]
Rendben, neki is állok ezek javításának.

**Comment by lbzs** [comment]
Ami még feltűnt, hogy egyik osztály konstruktorában sincs `super()` hívás. Nem okozhat ez gondot?

**Comment by Tajtesz** [comment]
Ezt a SonarQube is észrevette, és valóban általában célszerű megívni az ősosztály konstruktorát, mert esetlegesen létfontosságú konfigurációt tartalmazhat, vagy a visszatérési értékével kezdenünk kell valamit.

A kódot átvizsgálva viszont arra a következtetésre juthatunk, hogy az ősosztály konstruktorát teljesen fölösleges itt meghívni, nem történik benne konfiguráció, a visszatérési értékére sincs szükségünk. Véleményem szerint itt a fölösleges `super()` hívások csak zavaróak lennének, ne módosítsuk.
