### ISSUE TITLE
Manuális tesztek

### ISSUE THREAD

**Issue by Tajtesz** [BME-MIT-IET/Immutable-iet-2018#9]
A feladat célja az, hogy a rendelkezésünkre álló dokumentáció alapján (tehát nem a kódlefedettséggel kapcsolatos adatok alapján) saját teszteket tervezzünk meg, implementáljuk és dokumentáljuk is azokat.

Elsősorban a gyakrabban használt kollekciókra koncentrálva (pl. List, Map...) olyan teszteket kéne kitalálni, amik először csak egyszerűbb, de nélkülözhetetlen funkciókat tesztelnek, majd az egyre bonyolódó, elsőre talán nem egyértelmű funkciókat tesztelik.

A feladat megoldása során alapvetően az alábbi lépéseket kéne végrehajtani:

1. Teszt kitalálása
2. Teszt rövid leírása, céljainak meghatározása a feladathoz tartozó wiki oldalon
3. Teszt implementálása
4. GOTO 1.

A munka a `manualis-teszt` branchen fog folyni.

**Comment by Tajtesz** [comment]
Megírtam a `List`-hez tartozó tesztet, az alábbi 2 commit tartozik hozzá:

- fcb199827984a8e19137b98d3c3d00a6f761c03f

- 34afa8e91a709194e422d23bc64ca8ed1978c123

**Comment by Tajtesz** [comment]
A Stack teszt is elkészült:

- 33f633d79fc82068194ee53bcb176c13d92def81

**Comment by lbzs** [comment]
Map teszt kész: 

- 2fa46c57e148f0097cae38ed29828f7759d15ddd

**Comment by birolaszlo96** [comment]
OrderedSet-hez tartozó teszt is elkészült:

- [`1ac33b3`](https://github.com/BME-MIT-IET/Immutable-iet-2018/commit/1ac33b3bdae0141674c3780983a466d0270d1e5b)

**Comment by Tajtesz** [comment]
Amint látom megtörtént a merge is: #10 
Az issuet így lezárom.
